### ISSUE TITLE
git lfs error

### ISSUE THREAD

**Issue by Shine-ZX** [Babelscape/multinerd#1]
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access

**Comment by sted97** [comment]
Hi @Shine-ZX,

Thanks for pointing this out. We moved the files [here](https://drive.google.com/drive/u/2/folders/1i1zQ4Q3pKh6MOdr4lpQusdmd3428VhkU) on GDrive.

Best,
